#!/usr/bin/env python3
"""Parse completed Obsidian questionnaire and extract answers mapped to field_ids.

Reads the Obsidian markdown note generated by generate_questionnaire.py,
validates structural integrity, extracts answers for each job, and determines
submission readiness.

Usage:
    # Parse and show all jobs with readiness status:
    python scripts/parse_questionnaire.py --input "path/to/YYYY-MM-DD Applications.md"

    # Parse a specific job only:
    python scripts/parse_questionnaire.py --input "path/to/file.md" --job-id "2026-03-16_company_role"

Output JSON structure:
    {
      "jobs": [
        {
          "job_id": "...",
          "job_number": 1,
          "company": "...",
          "title": "...",
          "ats_platform": "...",
          "application_url": "...",
          "resume": "...",
          "ready": true,
          "errors": [],
          "fields": [
            {
              "field_id": "f1",
              "label": "...",
              "category": "auto_filled" | "auto_answered" | "user_input",
              "answer": "...",
              "type": "text" | "textarea" | "select" | ...,
              "required": true | false,
              "save_rule": "always" | "never" | null
            }
          ]
        }
      ]
    }
"""

import argparse
import json
import re
import sys
from pathlib import Path


def parse_questionnaire(content: str, target_job_id: str | None = None) -> dict:
    """Parse an Obsidian questionnaire markdown string.

    Args:
        content: The full markdown content of the questionnaire file.
        target_job_id: If provided, only parse this job's section.

    Returns:
        Dict with "jobs" key containing list of parsed job dicts.
    """
    jobs = []
    job_sections = split_job_sections(content)

    for section in job_sections:
        job = parse_job_section(section)
        if job is None:
            continue
        if target_job_id and job["job_id"] != target_job_id:
            continue
        jobs.append(job)

    return {"jobs": jobs}


def split_job_sections(content: str) -> list[str]:
    """Split the questionnaire into individual job sections.

    Each section starts with ## N. Company — Title <!-- job_id: ... -->
    """
    # Match ## followed by a number, dot, and the rest of the line
    pattern = r"^## \d+\."
    lines = content.split("\n")
    sections = []
    current_section_lines = []

    for line in lines:
        if re.match(pattern, line):
            if current_section_lines:
                sections.append("\n".join(current_section_lines))
            current_section_lines = [line]
        elif current_section_lines:
            current_section_lines.append(line)

    if current_section_lines:
        sections.append("\n".join(current_section_lines))

    return sections


def parse_job_section(section: str) -> dict | None:
    """Parse a single job section from the questionnaire.

    Returns a job dict or None if the section is unparseable.
    """
    lines = section.split("\n")
    errors = []

    # --- Parse header ---
    header_line = lines[0] if lines else ""
    job_id = extract_comment(header_line, "job_id")
    if not job_id:
        return None  # Can't identify the job without job_id

    # Extract job number, company, title from header
    header_match = re.match(
        r"^## (\d+)\.\s+(.+?)\s+<!--\s*job_id:", header_line
    )
    job_number = int(header_match.group(1)) if header_match else 0
    company_title = header_match.group(2).strip() if header_match else ""

    # Split company — title
    if " — " in company_title:
        company, title = company_title.split(" — ", 1)
    elif " - " in company_title:
        company, title = company_title.split(" - ", 1)
    else:
        company = company_title
        title = ""

    # --- Parse metadata lines ---
    ats_platform = ""
    application_url = ""
    resume = ""

    for line in lines[1:20]:  # Metadata is near the top
        stripped = line.strip()
        if stripped.startswith("**ATS Platform:**"):
            ats_platform = stripped.replace("**ATS Platform:**", "").strip()
        elif stripped.startswith("**Application URL:**"):
            application_url = stripped.replace("**Application URL:**", "").strip()
        elif stripped.startswith("**Resume:**"):
            resume = stripped.replace("**Resume:**", "").strip()

    # --- Parse fields from all subsections ---
    fields = []

    # Parse Auto-Filled section
    auto_filled_fields = parse_auto_section(section, "Auto-Filled from Profile", "auto_filled")
    fields.extend(auto_filled_fields)

    # Parse Auto-Answered section
    auto_answered_fields = parse_auto_section(section, "Auto-Answered from Rules", "auto_answered")
    fields.extend(auto_answered_fields)

    # Parse Needs Your Input section
    user_input_fields = parse_needs_input_section(section)
    fields.extend(user_input_fields)

    # --- Structural integrity validation ---
    # Check that all fields have field_ids
    for field in fields:
        if not field.get("field_id"):
            errors.append(
                f"Missing field_id comment for field '{field.get('label', 'unknown')}' "
                f"in job {job_number}. {company}"
            )

    # Check that user_input fields have Answer labels
    for field in user_input_fields:
        if field["category"] == "user_input" and "answer" not in field:
            errors.append(
                f"Missing Answer: label for question '{field.get('label', 'unknown')}' "
                f"in job {job_number}. {company}"
            )

    # --- Submission readiness ---
    ready = True
    for field in fields:
        if field.get("category") == "user_input" and field.get("required"):
            answer = (field.get("answer") or "").strip()
            if not answer:
                ready = False
                errors.append(
                    f"Required field '{field.get('label', 'unknown')}' "
                    f"({field.get('field_id', '?')}) has no answer"
                )

    return {
        "job_id": job_id,
        "job_number": job_number,
        "company": company.strip(),
        "title": title.strip(),
        "ats_platform": ats_platform,
        "application_url": application_url,
        "resume": resume,
        "ready": ready and len(errors) == 0,
        "errors": errors,
        "fields": fields,
    }


def parse_auto_section(section: str, header_name: str, category: str) -> list[dict]:
    """Parse an auto-filled or auto-answered section.

    Format:
        ### Auto-Filled from Profile
        - First Name: Dave <!-- field_id: f1 -->
        - Last Name: Fimek <!-- field_id: f2 -->
    """
    fields = []
    in_section = False

    for line in section.split("\n"):
        stripped = line.strip()

        if stripped.startswith("### ") and header_name in stripped:
            in_section = True
            continue

        if in_section and stripped.startswith("### "):
            break  # Next section started

        if in_section and stripped.startswith("- ") and "<!-- field_id:" in stripped:
            field_id = extract_comment(stripped, "field_id")
            # Parse "- Label: Value <!-- field_id: XX -->"
            content = stripped[2:]  # Remove "- " prefix
            content = re.sub(r"<!--.*?-->", "", content).strip()

            if ": " in content:
                label, answer = content.split(": ", 1)
            else:
                label = content
                answer = ""

            fields.append({
                "field_id": field_id,
                "label": label.strip(),
                "category": category,
                "answer": answer.strip(),
            })

    return fields


def parse_needs_input_section(section: str) -> list[dict]:
    """Parse the Needs Your Input section.

    Format:
        ### Needs Your Input

        **Q1: Why are you interested in this role?** <!-- field_id: f5 -->
        Type: textarea
        Required: yes
        Answer: I am passionate about...
        Save Rule: always

        **Q2: What is your desired salary?** <!-- field_id: f6 -->
        Type: text
        Required: no (skipped — field is optional)
    """
    fields = []
    in_section = False
    current_field = None

    for line in section.split("\n"):
        stripped = line.strip()

        if "### Needs Your Input" in stripped:
            in_section = True
            continue

        if in_section and stripped.startswith("### "):
            # Save current field before leaving section
            if current_field:
                fields.append(current_field)
                current_field = None
            break

        if not in_section:
            continue

        # New question starts with **Q
        if stripped.startswith("**Q") and re.match(r"\*\*Q\d+:", stripped):
            # Save previous field
            if current_field:
                fields.append(current_field)

            field_id = extract_comment(stripped, "field_id")

            # Extract label — try with field_id comment first, then without
            if field_id:
                label_match = re.match(
                    r"\*\*Q\d+:\s*(.+?)\*\*\s*<!--", stripped
                )
            else:
                label_match = re.match(
                    r"\*\*Q\d+:\s*(.+?)\*\*", stripped
                )

            label = label_match.group(1).strip() if label_match else ""

            current_field = {
                "field_id": field_id,
                "label": label,
                "category": "user_input",
                "answer": "",
                "type": "text",
                "required": False,
                "save_rule": None,
            }
            continue

        if current_field is None:
            continue

        # Parse field metadata lines
        if stripped.startswith("Type:"):
            current_field["type"] = stripped[5:].strip()
        elif stripped.startswith("Options:"):
            current_field["options"] = [
                o.strip() for o in stripped[8:].split(",")
            ]
        elif stripped.startswith("Required:"):
            req_text = stripped[9:].strip().lower()
            current_field["required"] = req_text.startswith("yes")
        elif stripped.startswith("Answer:"):
            # Answer may be on the same line or span multiple lines
            answer_text = stripped[7:].strip()
            current_field["answer"] = answer_text
            current_field["_reading_answer"] = True
        elif stripped.startswith("Save Rule:"):
            current_field.pop("_reading_answer", None)
            rule_text = stripped[10:].strip().lower()
            if rule_text in ("always", "never"):
                current_field["save_rule"] = rule_text
            else:
                current_field["save_rule"] = None
        elif current_field.get("_reading_answer") and stripped:
            # Continuation of multi-line answer
            if current_field["answer"]:
                current_field["answer"] += "\n" + stripped
            else:
                current_field["answer"] = stripped

    # Don't forget the last field
    if current_field:
        fields.append(current_field)

    # Clean up internal flags
    for field in fields:
        field.pop("_reading_answer", None)

    return fields


def extract_comment(line: str, key: str) -> str | None:
    """Extract a value from an HTML comment like <!-- key: value -->."""
    pattern = rf"<!--\s*{re.escape(key)}:\s*(.+?)\s*-->"
    match = re.search(pattern, line)
    return match.group(1).strip() if match else None


def get_ready_jobs(parsed: dict) -> list[dict]:
    """Filter to only jobs that are ready for submission."""
    return [job for job in parsed["jobs"] if job["ready"]]


def get_save_rules(parsed: dict) -> list[dict]:
    """Extract all Save Rule tags from parsed questionnaire.

    Returns list of dicts with: job_id, field_id, label, answer, save_rule
    """
    rules = []
    for job in parsed["jobs"]:
        for field in job["fields"]:
            if field.get("save_rule"):
                rules.append({
                    "job_id": job["job_id"],
                    "field_id": field["field_id"],
                    "label": field["label"],
                    "answer": field.get("answer", ""),
                    "save_rule": field["save_rule"],
                })
    return rules


def main():
    parser = argparse.ArgumentParser(
        description="Parse completed Obsidian questionnaire and extract answers"
    )
    parser.add_argument(
        "--input", required=True,
        help="Path to the Obsidian questionnaire markdown file"
    )
    parser.add_argument(
        "--job-id",
        help="Parse only this job's section (optional)"
    )

    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        content = f.read()

    result = parse_questionnaire(content, target_job_id=args.job_id)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
